### ISSUE TITLE
Bad behaviour - stop/profit closePosition=True

### ISSUE THREAD

**Issue by Eric-Bujeque** [Binance-docs/Binance_Futures_python#100]
I have a code that creates a buy order and then sets the take profit market and stop-loss market like:

`profit = account.client.post_order(symbol=symbol, side=OrderSide.SELL, ordertype=OrderType.TAKE_PROFIT_MARKET, positionSide=PositionSide.BOTH, stopPrice="2.4", closePosition=True)`

`stop = account.client.post_order(symbol=symbol, side=OrderSide.SELL, ordertype=OrderType.STOP_MARKET, positionSide=PositionSide.BOTH, stopPrice="2.2", closePosition=True)`

It works totally fine until one triggers. The problem is, as I have closePosition=True I expect that if stop loss is triggered it will close the take profit and vice-versa, but it is not happening. What happens is that it close the current position and stop-loss order, but it let the take profit opened, without position. Am I doing something wrong?

Screenshot 1: Everything is set fine:
![screenshot1](https://bujecket.s3.eu-west-3.amazonaws.com/temp/Screenshot+from+2021-02-21+20-20-26.png)

Screenshot 2: Orphan take-profit order with no position:
![screenshot2](https://bujecket.s3.eu-west-3.amazonaws.com/temp/Screenshot+from+2021-02-21+20-24-39.png)

**Comment by Vitve4** [comment]
It does exactly what it should - close the position. No one said that it would cancel the opposite order as well. These orders don't cancel each other. Unfortunately, as I know, binance API is not supporting OCO (OTOCO) orders for futures, though it seems logically to have such opportunity to open position with SL and TP just like in web/app interface.
