### ISSUE TITLE
how to close the ‘For develop’ info of ’print(request)‘

### ISSUE THREAD

**Issue by wdwlrz** [Binance-docs/Binance_Futures_python#108]
print("====== Request ======")
print(request)
PrintMix.print_data(request)
print("=====================")

how to cancle the develop mode ?

**Comment by rmdpadula** [comment]
Man....i did some changes in the source code to remove all this prints for my project. Maybe can help you out.
https://github.com/rmdpadula/Binance_Futures

Just remember that if you want to print at your own way, you need to put __dict__ at the end
Like:
When I push all get_open_orders() function, I do something like this:
for r in result:
        print(r.__dict__)

Hope help you in your project.

**Comment by wdwlrz** [comment]
> Man....i did some changes in the source code to remove all this prints for my project. Maybe can help you out.
> https://github.com/rmdpadula/Binance_Futures
> 
> Just remember that if you want to print at your own way, you need to put **dict** at the end
> Like:
> When I push all get_open_orders() function, I do something like this:
> for r in result:
> print(r.**dict**)
> 
> Hope help you in your project.
