### ISSUE TITLE
安裝問題The problem about installing

### ISSUE THREAD

**Issue by hi-Nobody** [Binance-docs/Binance_Futures_python#18]
當我安裝執行setup.py時，卻有這則錯誤訊息"error: package directory 'binance_f' does not exist"，請問我應該要如何解決呢?
Cloud u tell me how to solve the problem, emerging the error:"error: package directory 'binance_f' does not exist" when I install and execute "setup.py"?
Thank u
![安裝問題](https://user-images.githubusercontent.com/62271163/76844242-fb049580-6877-11ea-8b9b-2f671f09dfc3.JPG)

**Comment by 2pd** [comment]
try with `python3 setup.py install`

**Comment by hi-Nobody** [comment]
> try with `python3 setup.py install`

My OS is Win10, and ur suggestion is used in Linux
Thanks

**Comment by hi-Nobody** [comment]
I have solve this problem
