### ISSUE TITLE
How can I parse string?

### ISSUE THREAD

**Issue by jeongcatfish** [Binance-docs/Binance_Futures_python#31]
code :
result = request_client.get_mark_price(symbol="BTCUSDT")
print(type(result))

result:
{"symbol":"BTCUSDT","markPrice":"9178.31158160","lastFundingRate":"0.00089972","nextFundingTime":1588262400000,"time":1588235887000}
<class 'binance_f.model.markprice.MarkPrice'>

result look like Dictionary. 
so first time I try like this -> print(result["markPrice"]
and I failed..

If you guys know how to do it please let me know.
Thank you.

**Comment by vladb-metapack** [comment]
Result is an object.

`result.markPrice 
`
should work

**Comment by jeongcatfish** [comment]
> Result is an object.
> 
> `result.markPrice `
> should work


Thank you.
It works!  
I should learn python..

**Comment by imspyros** [comment]
What if "result" is a list?
