### ISSUE TITLE
constant.py

### ISSUE THREAD

**Issue by tommi33** [Binance-docs/Binance_Futures_python#4]
binance_f/model/constant.py
Please correct the ordertype values according to API definitions
STOP_LOSS >> STOP_MARKET
STOP_LOSS_LIMIT >> STOP
TAKE_PROFIT >>TAKE_PROFIT_MARKET
TAKE_PROFIT_LIMIT >> TAKE_PROFIT

**Comment by 2pd** [comment]
Fixed in #5
