### ISSUE TITLE
Error while attempting to Install

### ISSUE THREAD

**Issue by BBC132** [Binance-docs/Binance_Futures_python#42]
So i downloaded the files and it shows that there is a binance_f file exists in finder, but it claims it doesn't exist when I try installing. Please help me.

![Screen Shot 2020-05-27 at 10 11 51 PM](https://user-images.githubusercontent.com/14238195/83098260-58327980-a067-11ea-8d6c-a1d056f186f5.png)

**Comment by BBC132** [comment]
Also tried downloading another version with the same results

![Screen Shot 2020-05-27 at 10 30 25 PM](https://user-images.githubusercontent.com/14238195/83099135-b3656b80-a069-11ea-907e-08761a61e6b1.png)

**Comment by D50000** [comment]
can you just try:
```
cd /xxx/Binance_Futures_python/
python3 setup.py install
```
and check the result

**Comment by BBC132** [comment]
work like a charm thx :)
