### ISSUE TITLE
Cryptocurrency Pair Trading

### ISSUE THREAD

**Issue by morph3us-net** [Binance-docs/Binance_Futures_python#56]
Using the "get_exchange_information.py" example,
(https://github.com/Binance-docs/Binance_Futures_python/blob/master/example/market/get_exchange_information.py)
I only get the cryptocurrencie's values in USD.

Binance itself lets you trade for example Bitcoin to Litecoin (or anything else).

Am I overlooking something or does the API only support trading from and to USD?

Thank you very much for any clarification on this topic!

**Comment by MachineTrader** [comment]
Yes api is only for futures trading, not the normal exchange.

**Comment by morph3us-net** [comment]
Thank you very much for the info!

Could you kindly recommend me a library that supports that?
There are a few different ones out there, but I am not experienced enough to distinguish which one is trustworthy, supports everything needed and is stable enough.
Else I should close this issue.

**Comment by MachineTrader** [comment]
No problem..
I think it's this library that is the most recommended?
https://github.com/sammchardy/python-binance

**Comment by morph3us-net** [comment]
Unfortunately I already tried that one and couldn't even get the examples to work...
An issue, I posted there, went unanswered for almost a month now, so I searched for alternative libraries.

I will give it another try, though! It must be an issue on my side, I'm sure...
Thank you very much for taking your time, I wish you all the best and stay healthy!
