### ISSUE TITLE
print issue 

### ISSUE THREAD

**Issue by LYERO7** [Binance-docs/Binance_Futures_python#58]
I have this problem when i want to print a ticker from a list.
`bclient=RequestClient(api_key=api_key, secret_key=api_secret
result=bclient.get_symbol_price_ticker(symbol='BTCUSDT')
print(result[0])

[<binance_f.model.symbolprice.SymbolPrice object at 0x000001852A3308B0>]
`
Have anyone an idea why this happen ? Thanks

**Comment by just-a-normal-human** [comment]
Try this

```
import json
import jsonpickle

def get_ticker(symbol):
    tick= bclient.get_symbol_price_ticker(symbol)
    tick= jsonpickle.encode(t)
    tick= json.loads(t)
    tick= [c['price'] for c in tick][0]
    return tick

eth_price=get_ticker('ETHUSDT')
print(eth_price)
````

This will return a float

**Comment by LYERO7** [comment]
hey thank you for your reply, i tried your code it shows the following message : 
name 't' is not defined

**Comment by LYERO7** [comment]
I replaced t with tick and it worked, thank you man.

**Comment by just-a-normal-human** [comment]
Yess sorry, typo, I replaced "t" with "tick" in answer. No problem, happy to help!
