### ISSUE TITLE
Precision is over the maximum defined for this asset

### ISSUE THREAD

**Issue by congthuyen94** [Binance-docs/Binance_Futures_python#95]
I can not post an order with float quantity value. Even the precision is low.

The post_body is something like this:
url:/fapi/v1/order?symbol=XTZUSDT&side=BUY&type=MARKET&quantity=0.99&positionSide=LONG&recvWindow=60000&timestamp=1611848552560

**Comment by niyomalchaminda** [comment]
Me too having the same issue 

![Capturenewb](https://user-images.githubusercontent.com/26848543/108661487-f3bb2280-74f1-11eb-8d87-c46b55d62b78.PNG)

**Comment by niyomalchaminda** [comment]
if you use python, try below, pass quantity variable to API

quantity_before = 0.99
quantity="{:0.0{}f}".format(quantity_before , 5)

**Comment by kasahh** [comment]
> I can not post an order with float quantity value. Even the precision is low.
> 
> The post_body is something like this:
> url:/fapi/v1/order?symbol=XTZUSDT&side=BUY&type=MARKET&quantity=0.99&positionSide=LONG&recvWindow=60000&timestamp=1611848552560

did you find a solution to this problem?  niyomalchaminda solution didnt work for me. the order only goes through if there are no decimals in the price or quantity values

**Comment by kennychvz** [comment]
I don't know if this would work, but you could maybe make a try statement and try to make orders from a precision of 6 decimals to 0. So your code would try to make an order with a precision of 6 and if it doesn't work then it goes to 5 and 4 and so on. So you don't risk buying 1 btc as a whole if you can't have decimals in your quantity lol.

**Comment by kennychvz** [comment]
> 
> 
> I don't know if this would work, but you could maybe make a try statement and try to make orders from a precision of 6 decimals to 0. So your code would try to make an order with a precision of 6 and if it doesn't work then it goes to 5 and 4 and so on. So you don't risk buying 1 btc as a whole if you can't have decimals in your quantity lol.

Hi, I was finally able to solve this problem, basically every symbol has a different number of decimals it uses when calling how much quantity you want to buy, you can access directly this precision number and then round your number up to the necessary precision, this code here should solve your problem:

symbol = 'ETHUSD' #this can be any symbol you want
result = request_client.get_exchange_information() 
number_of_symbols = len(result.symbols) #number of symbols available to trade
precision = 0 #empty variable we will use later
        
for i in range(number_of_symbols): #we loop through all the different tickers
    if result.symbols[i].symbol == symbol: #we find our precise symbol
        precision = result.symbols[i].quantityPrecision #we find the precision number of our symbol

quantity_rounded = round(quantity, precision)
